name: micro_nonrandom
target supercategories:
- sky
box type: 
  name: nonrandom aggregated
  box ratio: 0.5
  num miniboxes: 10
number of boxes: 1
splits:
- name: train
  fraction: 0.001
- name: val
  fraction: 0.01