name: micro_nonrandom
target supercategories:
- sky
box type: 
  name: nonrandom aggregated
  ratio: 0.5
  num_miniboxes: 10
number of boxes: 10
splits:
- name: train
  fraction: 0.001
- name: val
  fraction: 0.01