agent: PUBoxAgent
supercategories:
- sky

# The MS COCO Stuff Dataset
size: 0.1

# Please take a look at https://github.com/abhay-venkatesh/cocostuff for setup
source: D:\code\data\cocostuff\dataset
destination: D:\code\data\filtered_datasets