agent: Stuff2018FixedAgent
supercategories: []

# The MS COCO Stuff Dataset
size fraction: 0.01

# Please take a look at https://github.com/abhay-venkatesh/cocostuff for setup
source: /home/abhay/code/data/cocostuff/dataset
destination root: /home/abhay/code/data/filtered_datasets/
